### ISSUE TITLE
avoid catching exception when not in main thread

### ISSUE THREAD

**Issue by 3nids** [wonder-sk/qgis-first-aid-plugin#12]
I got several QGIS crashes today and _first aid_ was the source of these... ;)

Here is a trace: https://pastebin.com/GM0Hpp4u

Would it be possible to avoid running outside of main thread?

**Comment by wonder-sk** [comment]
> Would it be possible to avoid running outside of main thread?

Or even better, catch the errors from worker threads, do not crash and report them! Fixed in version 2.1.1.
