### ISSUE TITLE
2.x compatibility?

### ISSUE THREAD

**Issue by nyalldawson** [wonder-sk/qgis-first-aid-plugin#20]
Is this still a requirement? There's a lot of code which could be cleaned up substantially if this could be dropped...

**Comment by wonder-sk** [comment]
Sounds good to me to drop 2.x compatibility code...

**Comment by mvaaltola** [comment]
I would agree it's time to drop the 2.x support. It would help get rid of the otherwise unnecessary dependencies on future and past.

**Comment by rduivenvoorde** [comment]
I think
https://github.com/wonder-sk/qgis-first-aid-plugin/commit/e6baa706f1d64ce4305cb268c4c9007d17ea58fb
broke the QGIS 2 compatibilty anyway. 

I installed QGIS 2.18 on a windows machine today (to test an old WPS plugin) and tried to install first-aid and got an exception on the line `from qgis.gui import QgsGui`

![Screenshot-20200925114115-769x495](https://user-images.githubusercontent.com/731673/94253077-10dccc80-ff25-11ea-975e-68e0a1c284f7.png)

I tested and 2.1.2 is still loading inn QGIS 2.18

Would be nice to keep a 2.1.2 around (so peeps like me can dig up a QGIS2 plugin they maybe want to port), but change the metadata of > 2.1.1 to max version 2.99 ?
