### ISSUE TITLE
UX with Blend of grey QGIS style

### ISSUE THREAD

**Issue by Gustry** [wonder-sk/qgis-first-aid-plugin#23]
Using the plugin with the theme Blend of grey make it quite difficult to read. I need to select the text to be able to read.

We can't read the error in the first screenshot.

![Capture d’écran de 2020-01-15 09-03-43](https://user-images.githubusercontent.com/1609292/72416077-2da9e900-3776-11ea-8700-388069438493.png)

With selection:
![Capture d’écran de 2020-01-15 09-05-50](https://user-images.githubusercontent.com/1609292/72416131-47e3c700-3776-11ea-9e86-44bf36160538.png)

**Comment by wonder-sk** [comment]
Hmm that's strange... aren't all labels supposed to have some light color set within that style?

**Comment by nyalldawson** [comment]
@gustry is this still an issue?

**Comment by Gustry** [comment]
I do not replicate anymore.
