### ISSUE TITLE
Python error 

### ISSUE THREAD

**Issue by Ludwig-K** [wonder-sk/qgis-first-aid-plugin#33]
After fresh install of the plugin on "QGis 3.28.2-Firenze" the attached Python-TypeError messages appears every time I load a python file into the debugger or I hover over the debugger-window.
![ksnip_20221223-204627](https://user-images.githubusercontent.com/5821720/209399712-397b8dcf-9a31-4081-a2fb-ce57b6f1d688.png)

**Comment by Ludwig-K** [comment]
The bug is in line 225 of debuggerwidget.py.
Original:
`painter.drawText(0, top, self.lineNumberArea.width() - self.fontMetrics().width('9'),`
corrected:
`painter.drawText(0, int(top), self.lineNumberArea.width() - self.fontMetrics().width('9'),`
I presume, that the actual Python/Qt is more type-strict then previous versions.

**Comment by nyalldawson** [comment]
Fixed by #34
