### ISSUE TITLE
If exception text is too long, dialog becomes very wide and cannot be shrunk

### ISSUE THREAD

**Issue by nyalldawson** [wonder-sk/qgis-first-aid-plugin#40]
The text in the exception label needs to be worded wrapable to avoid this

**Comment by Gustry** [comment]
Linked to https://github.com/wonder-sk/qgis-first-aid-plugin/pull/41 by @ZayneTomlins ?

**Comment by nyalldawson** [comment]
Fixed by https://github.com/wonder-sk/qgis-first-aid-plugin/pull/41
