### ISSUE TITLE
'ResourceWarning: unclosed file' from sourceview.py

### ISSUE THREAD

**Issue by pers-ephone** [wonder-sk/qgis-first-aid-plugin#46]
\firstaid\sourceview.py:43: ResourceWarning: unclosed file 
              self.setText(open(filename).read())
              

is there any reason to not use
```py
with open(filename) as file:
       self.setText(file.read())
```
?

**Comment by nyalldawson** [comment]
Absolutely no good reason not to 😝 ! 

can you file a pull request?

(There's quite a lot of older python 2 style code which could potentially be cleaned up in this plugin, if you spot others then all modernization requests are welcome!)
