### ISSUE TITLE
Plugin does not work in Windows OS

### ISSUE THREAD

**Issue by rdbath** [wonder-sk/qgis-first-aid-plugin#7]
If I use your plugin(v 2.0.1) in Linux OS it works fine but if I use it in Windows(7,64bit) it does not halt on breakpoints and can't be used for debugging. Is this a known issue? 
I tested it with several plugins to debug and on two different laptops.
Edit: If I run files manually (for example test_script.py in the plugin folder) the debugger halts on breakpoints but not in files that can't be run manually (part of plugins with import statements for example).

**Comment by dbenedetti** [comment]
I'm seeing this same issue. If I have some time, I will investigate further.
